services:
  flask_app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/templates:/app/templates:ro
      - ./app/translations:/app/translations:ro

    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:30160"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      - ./app/static:/app/static:ro
      - ./app/templates:/app/templates:ro
      - ./app/translations:/app/translations:ro

    depends_on:
      - flask_app
    networks:
      - app-network
    restart: always


networks:
  app-network:
    driver: bridge
